baseURL = "http://example.org/"
languageCode = "nl-nl"
title = "Bruiloft Tonke & Jonathan"
theme = "wedding"

[deployment]
order = [".jpg$", ".gif$"]
    [[deployment.targets]]
        name = "Azure"
        url = "azblob://$web"